# Generated by Django 2.0.3 on 2018-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presc',
            name='date',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='presc',
            name='Notes',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='presc',
            name='doctor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presc',
            name='medicine',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presc',
            name='patient',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
