# Generated by Django 2.0.3 on 2018-03-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presc', '0002_auto_20180326_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presc',
            name='Notes',
            field=models.TextField(null=True),
        ),
    ]
