# Generated by Django 2.0.2 on 2018-03-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERMODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('public', 'PUBLIC'), ('patient', 'PATIENT'), ('doctor', 'DOCTOR')], default='public', max_length=7)),
            ],
        ),
    ]
