# Generated by Django 2.0.2 on 2018-03-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
