# Generated by Django 2.0.2 on 2018-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0003_auto_20180307_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='aname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
