# Generated by Django 2.0.2 on 2018-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0004_usermodel_aname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='aname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
