# Generated by Django 2.0.2 on 2018-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0005_auto_20180307_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='bg',
            field=models.CharField(choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], default='o+', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='type',
            field=models.CharField(choices=[('Public', 'PUBLIC'), ('Patient', 'PATIENT'), ('Doctor', 'DOCTOR')], default='public', max_length=7),
        ),
    ]
