# Generated by Django 2.0.2 on 2018-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0010_auto_20180307_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extra',
            name='qu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
