# Generated by Django 2.0.2 on 2018-03-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0012_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='timezone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
