# Generated by Django 2.0.2 on 2018-03-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0014_auto_20180308_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bg',
            field=models.CharField(choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=5, null=True),
        ),
    ]
