# Generated by Django 2.0.2 on 2018-03-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0015_auto_20180308_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='auth',
            field=models.TextField(null=True),
        ),
    ]
