# Generated by Django 2.0.3 on 2018-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledet', '0016_usermodel_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
